// @flow
'use strict';

const path = require('path');

const repoDir = path.join(__dirname, '../..');
const buildDir = path.join(repoDir, 'build');
const sourceDir = path.join(repoDir, 'src');

const config = {
  entry: path.join(sourceDir, 'index.jsx'),
  module: {
    loaders: [
      // Transform .jsx files to ES5 with Babel.
      {
        test: /\.jsx$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          plugins: [
            'ramda'
          ],
          presets: [
            'es2015',
            'react',
            'stage-2'
          ]
        }
      },
      // Transform .js files to ES5 with Babel.
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          plugins: [
            'ramda',
            'transform-flow-strip-types'
          ],
          presets: [
            'es2015',
            'stage-2'
          ]
        }
      }
    ]
  },
  // Configuration for assets generated by the build process.
  output: {
    // Name of the entry assets to generate.
    filename: 'app.js',
    // Output directory to write the assets to.
    path: buildDir
  },
  resolve: {
    extensions: [
      '',
      '.js',
      '.jsx'
    ],
    modulesDirectories: [
      'node_modules'
    ],
    root: sourceDir
  }
};

module.exports = config;
